
- name: 'make sure mysql are installed'
  yum: 
    name: MySQL-python 
    state: installed
  when: ansible_os_family == "RedHat"
  register: installed
  retries: 3

- name: 'verify presence of jdbc connector for mysql'
  stat: 
    path: "{{artifactory_home}}/tomcat/lib/{{mysql_jdbc_base}}-bin.jar"
  register: jdbc_installed

- name: 'download jdbc connector for mysql'
  get_url: 
    url: "{{mysql_jdbc_url}}" 
    dest: /tmp
  retries: 3
#  when: features.mysql and not ant_installed.stat.exists

- name: 'untar jdbc connector for mysql'
  command: "tar xfvz /tmp/{{ mysql_jdbc_base }}.tar.gz -C /tmp"

- name: 'enable jdbc connector for mysql'
  command: "mv /tmp/{{ mysql_jdbc_base }}/{{ mysql_jdbc_base }}-bin.jar {{ artifactory_home }}/tomcat/lib"

- name: 'create artifactory database in mysql'
  mysql_db: 
    name: "{{ artifactory_database_db }}"
    login_host: "{{ artifactory_database_hostname }}"
    login_password: "{{ artifactory_database_hostname_pass }}"
    login_user: "{{ artifactory_database_main_username }}"
    encoding: "{{ artifactory_database_encoding }}"
    state: present

- name: 'create artifactory database user in mysql'
  mysql_user: 
    host: "{{ artifactory_host_ip }}"
    login_host: "{{ artifactory_database_hostname }}" 
    login_user: "{{ artifactory_database_main_username }}" 
    login_password: "{{ artifactory_database_hostname_pass }}" 
    name: "{{ artifactory_username }}"
    password: "{{ artifactory_password }}" 
    priv: "{{ artifactory_database_db }}.*:ALL" 
    state: present

- name: 'enable mysql driver'
  template: 
    src: storage_mysql.j2 
    dest: "{{artifactory_home}}/etc/storage.properties" 
    owner: root 
    group: root 
    mode: 0644
