---
- name: "make sure mysql is installed"
  yum: 
    name: MySQL-python 
    state: installed
  register: installed
  retries: 3
  when: ansible_os_family == "RedHat"

- name: "verify presence of jdbc connector for mysql"
  stat: 
    path: "{{ artifactory_runtime_dir }}/tomcat/lib/{{ artifactory_mysql_jdbc_base }}-bin.jar"
  register: jdbc_installed

- debug: var=jdbc_installed

- get_url:
    url: "{{ artifactory_mysql_jdbc_url }}"
    dest: /tmp
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    mode: 0755

- unarchive:
    src: "/tmp/{{ artifactory_mysql_jdbc_base }}.tar.gz"
    dest: /tmp/
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    mode: 0755
    remote_src: True

#- unarchive:
#    src: "{{ artifactory_mysql_jdbc_url }}"
#    dest: /tmp/
#    owner: "{{ artifactory_user }}"
#    group: "{{ artifactory_group }}"
#    validate_certs: no
#    remote_src: True

#- name: "download jdbc connector for mysql"
#  get_url:
#    url: "{{ artifactory_mysql_jdbc_url }}"
#    dest: /tmp
#  retries: 3
#  when: features.mysql and not ant_installed.stat.exists

#- name: "untar jdbc connector for mysql"
#  command: "tar xfvz /tmp/{{ artifactory_mysql_jdbc_base }}.tar.gz -C /tmp"

- name: "enable jdbc connector for mysql"
  copy:
    src: "/tmp/{{ artifactory_mysql_jdbc_base }}/{{ artifactory_mysql_jdbc_base }}-bin.jar"
    dest: "{{ artifactory_runtime_dir }}/tomcat/lib"
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    mode: 0755
    remote_src: True

- name: "create artifactory database"
  mysql_db:
    name: "{{ artifactory_db_name  }}"
    login_host: "{{ artifactory_db_host }}"
    login_user: "{{ artifactory_db_root_user }}"
    login_password: "{{ artifactory_db_root_pass }}"
    encoding: "{{ artifactory_db_encoding }}"
    state: present

- name: 'create artifactory database'
  mysql_user:
    host: "{{ artifactory_db_host }}"
    login_host: "{{ artifactory_db_host }}"
    login_user: "{{ artifactory_db_root_user }}"
    login_password: "{{ artifactory_db_root_pass }}"
    name: "{{ artifactory_db_name  }}"
    password: "{{ artifactory_db_pass }}"
    priv: "{{ artifactory_db_name }}.*:ALL"
    host: "%"
    state: present

- name: "create etc directory"
  file:
    state: directory
    path: "{{ artifactory_runtime_dir }}/etc/"
    mode: 0755
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"

- name: "enable mysql driver"
  template:
    src: storage_mysql.j2
    dest: "{{ artifactory_conf_dir }}/db.properties"
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    mode: 0644

- name: "enable mysql driver"
  template:
    src: storage_mysql.j2
    dest: "{{ artifactory_conf_dir }}/storage.properties"
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}"
    mode: 0644
