
- name: "make sure mysql is installed"
  yum: 
    name: MySQL-python 
    state: installed
  when: ansible_os_family == "RedHat"
  register: installed
  retries: 3

- name: "verify presence of jdbc connector for mysql"
  stat: 
    path: "{{ artifactory_home }}/tomcat/lib/{{ artifactory_mysql_jdbc_base }}-bin.jar"
  register: jdbc_installed

- name: "download jdbc connector for mysql"
  get_url: 
    url: "{{ artifactory_mysql_jdbc_url }}" 
    dest: /tmp
  retries: 3
#  when: features.mysql and not ant_installed.stat.exists

- name: "untar jdbc connector for mysql"
  command: "tar xfvz /tmp/{{ artifactory_mysql_jdbc_base }}.tar.gz -C /tmp"

- name: "enable jdbc connector for mysql"
  command: "mv /tmp/{{ artifactory_mysql_jdbc_base }}/{{ artifactory_mysql_jdbc_base }}-bin.jar {{ artifactory_home }}/tomcat/lib"

- name: 'create artifactory database in mysql'
  mysql_db: 
    name: "{{ artifactory.db_name  }}"
    login_host: "{{ artifactory.db_hostname }}" 
    login_user: "{{ artifactory.db_root_user }}" 
    login_password: "{{ artifactory.db_root_pass }}" 
    encoding: "{{ artifactory.db_encoding }}"
    state: present

- name: 'create artifactory database user in mysql'
  mysql_user: 
    host: "{{ artifactory.db_hostname }}"
    login_host: "{{ artifactory.db_hostname }}" 
    login_user: "{{ artifactory.db_root_user }}" 
    login_password: "{{ artifactory.db_root_pass }}" 
    name: "{{ artifactory.db_name  }}"
    password: "{{ artifactory.db_pass }}" 
    priv: "{{ artifactory.db_name }}.*:ALL" 
    host: "%"
    state: present

- name: "create etc directory"
  file:
    state: directory
    path: "{{ artifactory_home }}/etc/"
    mode: 0755
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}" 


- name: "enable mysql driver"
  template: 
    src: storage_mysql.j2 
    dest: "{{ artifactory_conf_dir }}/db.properties" 
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}" 
    mode: 0644

- name: "enable mysql driver"
  template: 
    src: storage_mysql.j2 
    dest: "{{ artifactory_conf_dir }}/storage.properties" 
    owner: "{{ artifactory_user }}"
    group: "{{ artifactory_group }}" 
    mode: 0644
