---
- name: "Install nginx"
  package:
    name: nginx
    state: installed

  # Set (httpd_can_network_connect) flag on and keep it persistent across reboots
- seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: "Check ssl|cert existence"
  stat:
    path: "{{ item }}"
  when: artifactory_ssl

- name: "Check ssl key"
  stat:
    path: "{{ artifactory_ssl_cert_dir }}/{{ artifactory_ssl_key_filename }}"
  register: key
  when: artifactory_ssl

- name: "Check ssl cert"
  stat:
    path: "{{ artifactory_ssl_cert_dir }}/{{ artifactory_ssl_cert_filename }}"
  register: cert
  when: artifactory_ssl

- name: "Copy certificated into /etc/ssl/certs"
  copy:
    src: "{{ item }}"
    dest: /etc/ssl/certs
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ ssl_cert }}"
    - "{{ ssl_key }}"
  when: ((artifactory_ssl) and (not key.exists or not cert.exists))

- name: "nginx | Artifactory vhost configuration"
  template:
    src: "artifactory-nginx.conf.j2"
    dest: "/etc/nginx/conf.d/default.conf"

- name: "nginx | global configuration"
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"

- name: "start & enable service"
  service:
    name: nginx
    state: restarted
    enabled: yes